name: 💡 Feature request
description: Got a suggestion for a new idea/feature ?
labels: ["enhancement"]
body:
  - type: textarea
    id: whatsnew
    attributes:
      label: What's new?
      description: If the proposal involves a new component or a redesign of a previous component.
    validations:
      required: true

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
